FP-699: Prototype: setup static pages
department-for-transport-public/findtransportdata-prototypes pull request #3
Opened 2023-03-13 15:13 UTC by m-asim-iqbal

Please review this PR:
@dynamicmonkeys @radicalgeek

2023-03-14 10:47 UTC, radicalgeek approved these changes

2023-03-21 21:39 UTC, dynamicmonkeys requested changes
@m-asim-iqbal good work, very helpful. A handful of tweaks please for titles etc to align

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/500.html
> +            Oops,something went wrong at {{" - " +requestId if requestId else "" }}
Given this is just a prototype, does it need this?

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/accessibility.html
> +                This statement only applies to the Find Transport Data service, available at <a href="https://findtransportdata.dft.gov.uk">https://findtransportdata.dft.gov.uk</a>.
Can you please knock this href to being the root of the prototype please

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/components/footer.njk
> +  classes:"ftd-footer",
I can't see where we leverage this as a JS hook nor have a custom style for it, if we don't, can you please remove it so we can nurture this to be less custom, less ftd-* and nap-*, TY

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/404.html
> +  GOV.UK 404 page template – {{ serviceName }} – GOV.UK Prototype Kit
Please align the pageTitle with the prod one, wrapping in serviceName as appropriate

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/500.html
> +  GOV.UK 500 page template – {{ serviceName }} – GOV.UK Prototype Kit
Please align the pageTitle with the prod one, wrapping in serviceName as appropriate

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/accessibility.html
> +  GOV.UK accessibility template – {{ serviceName }} – GOV.UK Prototype Kit
Please align the pageTitle with the prod one, wrapping in serviceName as appropriate

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/cookies.html
> +  GOV.UK cookies page template – {{ serviceName }} – GOV.UK Prototype Kit
Please align the pageTitle with the prod one, wrapping in serviceName as appropriate

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/cookies.html
> +                <form data-module="cookie-settings" action="javascript:saveCookieChoice()">
Does saveCookieChoice hook up?

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/homepage.html
> +  GOV.UK homepage template – {{ serviceName }} – GOV.UK Prototype Kit
Please align the pageTitle with the prod one, wrapping in serviceName as appropriate

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/homepage.html
> +        <span class="govuk-caption-l ftd-small-heading">Find transport data</span>
.ftd-small-heading: The sass for this is missing :)

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/layouts/main.html
> +<form action="/browse/" method="get">
/browse/ should be /browse so Google et al don't see it as a separate page, if it's like this in the main repo then a ticket needs raising to mop up

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/privacy.html
> +  GOV.UK privacy page template – {{ serviceName }} – GOV.UK Prototype Kit
Please align title

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/roadmap.html
> +  GOV.UK roadmap page template – {{ serviceName }} – GOV.UK Prototype Kit
Please align pageTitle

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/roadmap.html
> +  html: 'This is a new service – your <a class="govuk-link" href="#">feedback</a> will help us to improve it.'
If this # href is right, then this needs mopping up on the main repo

2023-03-21 21:39 UTC, dynamicmonkeys commented on app/views/terms-and-conditions.html
> +  GOV.UK term and conditions page template – {{ serviceName }} – GOV.UK Prototype Kit
Please align

2023-03-24 09:30 UTC, m-asim-iqbal commented on app/views/500.html
> +            Oops,something went wrong at {{" - " +requestId if requestId else "" }}
Changed to static string

2023-03-24 09:30 UTC, m-asim-iqbal commented on app/views/accessibility.html
> +                This statement only applies to the Find Transport Data service, available at <a href="https://findtransportdata.dft.gov.uk">https://findtransportdata.dft.gov.uk</a>.
Changed the href to "/"

2023-03-24 09:32 UTC, m-asim-iqbal commented on app/views/components/footer.njk
> +  classes:"ftd-footer",
Removed classes

2023-03-24 09:35 UTC, m-asim-iqbal commented on app/views/404.html
> +  GOV.UK 404 page template – {{ serviceName }} – GOV.UK Prototype Kit
Changed page title to "GOV.UK - Find transport data"

2023-03-24 09:35 UTC, m-asim-iqbal commented on app/views/500.html
> +  GOV.UK 500 page template – {{ serviceName }} – GOV.UK Prototype Kit
Changed page title to "GOV.UK - Find transport data"

2023-03-24 09:35 UTC, m-asim-iqbal commented on app/views/layouts/main.html
> +<form action="/browse/" method="get">
Updated

2023-03-24 09:35 UTC, m-asim-iqbal commented on app/views/privacy.html
> +  GOV.UK privacy page template – {{ serviceName }} – GOV.UK Prototype Kit
Changed page title to "GOV.UK - Find transport data"

2023-03-24 09:35 UTC, m-asim-iqbal commented on app/views/roadmap.html
> +  GOV.UK roadmap page template – {{ serviceName }} – GOV.UK Prototype Kit
Changed page title to "GOV.UK - Find transport data"

2023-03-24 09:36 UTC, m-asim-iqbal commented on app/views/roadmap.html
> +  html: 'This is a new service – your <a class="govuk-link" href="#">feedback</a> will help us to improve it.'
updated href to smartsurvey url

2023-03-24 09:48 UTC, m-asim-iqbal commented on app/views/terms-and-conditions.html
> +  GOV.UK term and conditions page template – {{ serviceName }} – GOV.UK Prototype Kit
Updated

2023-03-24 09:48 UTC, merged