FP-679: Catch-up Prototype to current Facade functionality
department-for-transport-public/findtransportdata-prototypes pull request #4
Opened 2023-03-29 06:52 UTC by m-asim-iqbal

- Dataset edit page added with static data.
- On pressing the Delete button, a box appears for confirmation.
- The edit button takes the page to a static edit dataset page.
- Login Page added.
- Login Error Page added.
- User Dashboard Page added
- Publisher Requested Page added

Please review this PR:
@dynamicmonkeys @radicalgeek

2023-03-29 07:36 UTC, dynamicmonkeys requested changes
Just one change & a Q on Slack re: select component

2023-03-29 07:36 UTC, dynamicmonkeys commented on app/config.json
> +  "serviceName": "Find Transport Data - GOV.UK"
This should be stuck as `Find Transport Data` to reflect the GDS Service Name

2023-03-29 07:55 UTC, m-asim-iqbal commented on app/config.json
> +  "serviceName": "Find Transport Data - GOV.UK"
On the current prod (CKAN) the page title is "Find Trasport Data - GOV.UK"

2023-04-03 08:14 UTC, dynamicmonkeys commented on app/config.json
> +  "serviceName": "Find Transport Data - GOV.UK"
Hi, I've compared a number of services and the guidance and there's no definitive answer anymore!

2023-04-03 08:15 UTC, merged